name: CICD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on:
         ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Build Project
      run: mvn clean install -DskipTests
    - name: Login to docker hub
      run: docker login -u "${{secrets.DOCKER_USERNAME}}" -p "${{secrets.DOCKER_PASSWORD}}"
    - name: Build Docker Image and Create Container
      run: |
          docker build -t armah/mortgagecalc-spring-boot-docker .
          docker tag armah/mortgagecalc-spring-boot-docker:latest armah/mortgagecalc-spring-boot-docker:first-image
          docker push armah/mortgagecalc-spring-boot-docker:first-image
          docker create --name mortgagecalc-container armah/mortgagecalc-spring-boot-docker:first-image
          docker start mortgagecalc-container
          
    - name: Publish image to docker hub
      run: |
        docker pull armah/mortgagecalc-spring-boot-docker:first-image

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from docker hub
        run: docker pull armah/mortgagecalc-spring-boot-docker:first-image
      - name: Delete old container
        run: docker rm -f mortgagecalc-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name mortgagecalc-container armah/mortgagecalc-spring-boot-docker:first-image

